### ISSUE TITLE
Reprojection error assessment

### ISSUE THREAD

**Issue by JimCircadian** [icenet-ai/icenet-geoapi#7]
Mentioned by @tom-andersson

Task for someone who's keen in the future, but as we're reprojecting back to lat-lon from EASE, consider how much error we might be introducing...

**Comment by jemrobinson** [comment]
If you run through the current example notebook you can see that the EASE -> WGS -> EASE round trip introduces some millimetre-level errors, for example:

`4950000 5400000` -> `135.13294 16.62370` -> `4950000.001 5400000.001`

**Comment by JimCircadian** [comment]
This seems like a pretty broad issue that isn't likely to be addressed under here, so closing as a wontfix
